version: '2'
services:
  app:
    build: .
    working_dir: /backend
    environment:
      NODE_ENV: test
    tty: true
    links:
      - mongo
  mongo:
    image: mongo:3.2
    ports:
      - "27017:27017"